<?php
if( function_exists('acf_add_local_field_group') ):
acf_add_local_field_group(array(
	'key' => 'group_5c4fa33db5781',
	'title' => 'Form Details',
	'fields' => array(
		array(
			'key' => 'field_5c4fa344b2a91',
			'label' => 'Form Proper',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c4fa358b2a92',
			'label' => 'Fields',
			'name' => 'fields',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5c4fa399b2a93',
			'min' => 1,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Field',
			'sub_fields' => array(
				array(
					'key' => 'field_5c4fa551b2a96',
					'label' => 'General',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5c4fa399b2a93',
					'label' => 'Label',
					'name' => 'label',
					'type' => 'text',
					'instructions' => 'The label this field will use when displayed in the front end.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c4fa3f3b2a94',
					'label' => 'Type',
					'name' => 'type',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'text' => 'Single Line Text',
						'par' => 'Multi-line Text',
						'menu' => 'Menu Field',
						'checkbox' => 'Tick Box',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5c4fa322b1abe',
					'label' => 'CMS Key',
					'name' => 'key',
					'type' => 'text',
					'instructions' => 'The key for this field when submitted into the CMS.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c4fa434b2a95',
					'label' => 'Behaviour',
					'name' => 'require',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Required',
					'ui_off_text' => 'Normal',
				),
				array(
					'key' => 'field_5c4fa5beb2a97',
					'label' => 'Text Attributes',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5c4fa3f3b2a94',
								'operator' => '==',
								'value' => 'text',
							),
						),
						array(
							array(
								'field' => 'field_5c4fa3f3b2a94',
								'operator' => '==',
								'value' => 'par',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5c4fa5e3b2a99',
					'label' => 'Filter',
					'name' => 'filter',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5c4fa3f3b2a94',
								'operator' => '!=',
								'value' => 'par',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'none' => '---',
						'email' => 'Email Address',
						'phone' => 'Phone Number',
						'postal-code' => 'Postal Code',
						'url' => 'Web Address',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5c4fa82ee7d85',
					'label' => 'Send an autoreply?',
					'name' => 'has-autoreply',
					'type' => 'true_false',
					'instructions' => 'Send an autoreply to the email listed on this field when the form is submitted.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5c4fa3f3b2a94',
								'operator' => '!=',
								'value' => 'par',
							),
							array(
								'field' => 'field_5c4fa5e3b2a99',
								'operator' => '==',
								'value' => 'email',
							),
							array(
								'field' => 'field_5f9357958e082',
								'operator' => '!=',
								'value' => ''
							)
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Yes',
					'ui_off_text' => 'No',
				),
				array(
					'key' => 'field_5c4fa122b9aae',
					'label' => 'Autoreply Addressee',
					'name' => 'autoreply-name',
					'type' => 'text',
					'instructions' => 'The name used to addressed the receipient of this autoreply email. To use a value on this form as part of the message, use the shortcode <span style="font-family: \'courier new\';">[formvalue]</span>. For example: <span style="font-family: \'courier new\';">[formvalue name="first-name"]</span>.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5c4fa5e3b2a99',
								'operator' => '==',
								'value' => 'email',
							),
							array(
								'field' => 'field_5c4fa82ee7d85',
								'operator' => '==',
								'value' => 1,
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Registrant',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c4fa322b9aae',
					'label' => 'Autoreply Subject',
					'name' => 'autoreply-subject',
					'type' => 'text',
					'instructions' => 'The text that appears as the subject of the email being sent to the address.',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5c4fa5e3b2a99',
								'operator' => '==',
								'value' => 'email',
							),
							array(
								'field' => 'field_5c4fa82ee7d85',
								'operator' => '==',
								'value' => 1,
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c06ebde220b7',
					'label' => 'Autoreply Thumbnail',
					'name' => 'autoreply-thumbnail',
					'type' => 'image',
					'instructions' => 'The image that appears in the autoresponse email.',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5c4fa5e3b2a99',
								'operator' => '==',
								'value' => 'email',
							),
							array(
								'field' => 'field_5c4fa82ee7d85',
								'operator' => '==',
								'value' => 1,
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'full',
					'library' => 'all',
					'min_width' => 650,
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5c1fa7e0e7c82',
					'label' => 'Autoreply Message',
					'name' => 'autoreply-copy',
					'type' => 'repeater',
					'instructions' => 'The text that appear on the autoreply message after this form has been submitted. To use a value on this form as part of the message, use the shortcode <span style="font-family: \'courier new\';">[formvalue]</span>. For example: <span style="font-family: \'courier new\';">[formvalue name="first-name"]</span>.',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5c4fa5e3b2a99',
								'operator' => '==',
								'value' => 'email',
							),
							array(
								'field' => 'field_5c4fa82ee7d85',
								'operator' => '==',
								'value' => 1,
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_5c4fa5e3b1a99',
					'min' => 1,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add Section',
					'sub_fields' => array(
						array(
							'key' => 'field_5c4fa5e3b1a99',
							'label' => 'Format',
							'name' => 'email-format',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'paragraph' => 'Body Text',
								'h1' => 'Large Heading',
								'h2' => 'Sub Heading',
								'image' => 'Image',
								'html' => 'HTML Content',
								'table' => 'Table'
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5c4faa1be6038',
							'label' => 'Text',
							'name' => 'email-copy',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5c4fa5e3b1a99',
										'operator' => '!=',
										'value' => 'table',
									),
									array(
										'field' => 'field_5c4fa5e3b1a99',
										'operator' => '!=',
										'value' => 'image',
									),
									array(
										'field' => '',
										'operator' => '!=',
										'value' => 'html'
									)
								)
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '3',
							'new_lines' => '',
						),
						array(
							'key' => 'field_5c06ebde220b1',
							'label' => 'Image',
							'name' => 'email-body-image',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5c4fa5e3b1a99',
										'operator' => '==',
										'value' => 'image',
									)
								)
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'preview_size' => 'full',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5f99bffa34aa8',
							'label' => 'HTML',
							'name' => 'email-html',
							'type' => 'acf_code_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5c4fa5e3b1a99',
										'operator' => '==',
										'value' => 'html',
									)
								)
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'mode' => 'text/html',
							'theme' => 'default',
						),
						array(
							'key' => 'field_5c4fa322b9abe',
							'label' => 'Heading',
							'name' => 'email-table-heading',
							'type' => 'text',
							'instructions' => 0,
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5c4fa5e3b1a99',
										'operator' => '==',
										'value' => 'table',
									)
								)
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5c0fa7e0e7c82',
							'label' => 'Table Content',
							'name' => 'table-data',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5c4fa5e3b1a99',
										'operator' => '==',
										'value' => 'table',
									)
								)
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_5c4fa122b9abe',
							'min' => 1,
							'max' => 0,
							'layout' => 'table',
							'button_label' => 'Add Row',
							'sub_fields' => array(
								array(
									'key' => 'field_5c4fa122b9abe',
									'label' => 'Heading',
									'name' => 'table-heading',
									'type' => 'text',
									'instructions' => 0,
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5c4fa122b9a1e',
									'label' => 'Value',
									'name' => 'table-value',
									'type' => 'text',
									'instructions' => 0,
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								)
							),
						)
					),
				),
				array(
					'key' => 'field_5c4fa6f4b2a9b',
					'label' => 'Number of Lines',
					'name' => 'height',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5c4fa3f3b2a94',
								'operator' => '!=',
								'value' => 'text',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 1,
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_5c4fa739b2a9d',
					'label' => 'Menu Attributes',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5c4fa3f3b2a94',
								'operator' => '==',
								'value' => 'menu',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5c4fa82ee7c85',
					'label' => 'Type',
					'name' => 'radio',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Radio Buttons',
					'ui_off_text' => 'Dropdown Box',
				),
				array(
					'key' => 'field_5c4fa7e0e7c82',
					'label' => 'Choices',
					'name' => 'values',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_5c4fa80de7c83',
					'min' => 1,
					'max' => 0,
					'layout' => 'table',
					'button_label' => 'Add Option',
					'sub_fields' => array(
						array(
							'key' => 'field_5c4fa80de7c83',
							'label' => 'Label',
							'name' => 'label',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5c4fa814e7c84',
							'label' => 'Value',
							'name' => 'value',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array(
					'key' => 'field_5c4fa9ede6036',
					'label' => 'Tick Box Attributes',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5c4fa3f3b2a94',
								'operator' => '==',
								'value' => 'checkbox',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5c4faa06e6037',
					'label' => 'Tickbox Type',
					'name' => 'hide-label',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Tick Box',
					'ui_off_text' => 'Toggle',
				),
				array(
					'key' => 'field_5c4faa3be6038',
					'label' => 'Copy Text',
					'name' => 'copy_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5c4faa06e6037',
								'operator' => '==',
								'value' => '1',
							)
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_5c4faa59e6039',
					'label' => 'Ticked Value',
					'name' => 'value',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c4faa5226039',
					'label' => 'Unticked Value',
					'name' => 'unvalue',
					'type' => 'text',
					'instructions' => 'Leave blank if you wish not to submit this value unticked.',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5c4faa06e6037',
								'operator' => '!=',
								'value' => '1',
							)
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5c52112875d45',
			'label' => 'Text on the "Submit" Button',
			'name' => 'submit',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Submit',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fb42f5d5f481',
			'label' => 'Hidden Fields',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5fb42f6d5f482',
			'label' => 'Field Data',
			'name' => 'hidden',
			'type' => 'repeater',
			'instructions' => 'Sets hidden fields that will be submitted along with every submission of this form.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5fb42fb75f483',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Field',
			'sub_fields' => array(
				array(
					'key' => 'field_5fb42fb75f483',
					'label' => 'Name',
					'name' => 'name',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb42fc55f484',
					'label' => 'Value',
					'name' => 'value',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5c4faaabc5503',
			'label' => 'Submission Details',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c4faabcc5504',
			'label' => 'Receive Submissions through Email',
			'name' => 'receiver',
			'type' => 'email',
			'instructions' => 'Leave blank if you do not want to receive submissions via email.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Email Address',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5c5212ca1b2e3',
			'label' => 'Sender Credentials',
			'name' => 'smtp-details',
			'type' => 'group',
			'instructions' => 'Credentials needed to use proper email handling.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5f9357958e082',
					'label' => 'Sender Address',
					'name' => 'smtp-email',
					'type' => 'email',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5e277eea9460c',
					'label' => 'Email Protocol',
					'name' => 'is-smtp',
					'type' => 'true_false',
					'instructions' => 'Choose a protocol to be used for sending emails.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f9357958e082',
								'operator' => '!=empty'
							)
						)
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'SMTP (Host)',
					'ui_off_text' => 'Mailer (PHP)',
				),
				array(
					'key' => 'field_5c9fa39ab2a93',
					'label' => 'SMTP Login',
					'name' => 'smtp-login',
					'type' => 'text',
					'instructions' => 'The SMTP login username for the sender. Leave blank if it’s the same as the sender’s email address.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f9357958e082',
								'operator' => '!=empty'
							),
							array(
								'field' => 'field_5e277eea9460c',
								'operator' => '==',
								'value' => 1
							)
						)
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'The same as the sender’s email address.',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c9fa39ab2a96',
					'label' => 'SMTP Password',
					'name' => 'smtp-password',
					'type' => 'password',
					'instructions' => 'The password for sender’s email address.',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f9357958e082',
								'operator' => '!=empty'
							),
							array(
								'field' => 'field_5e277eea9460c',
								'operator' => '==',
								'value' => 1
							)
						)
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c7fa39ab2a93',
					'label' => 'SMTP Host URL',
					'name' => 'smtp-server',
					'type' => 'text',
					'instructions' => 'The SMTP server URL for the sender.',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f9357958e082',
								'operator' => '!=empty'
							),
							array(
								'field' => 'field_5e277eea9460c',
								'operator' => '==',
								'value' => 1
							)
						)
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c58feda928e3',
					'label' => 'SMTP Port',
					'name' => 'smtp-port',
					'type' => 'number',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f9357958e082',
								'operator' => '!=empty'
							),
							array(
								'field' => 'field_5e277eea9460c',
								'operator' => '==',
								'value' => 1
							)
						)
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 465,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 0,
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_5e271eea9460c',
					'label' => 'Security',
					'name' => 'is-ssl',
					'type' => 'true_false',
					'instructions' => 'Sets the security protocol for sending emails.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f9357958e082',
								'operator' => '!=empty'
							),
							array(
								'field' => 'field_5e277eea9460c',
								'operator' => '==',
								'value' => 1
							)
						)
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'SSL/TLS',
					'ui_off_text' => 'Default',
				),
			)
		),
		array(
			'key' => 'field_5c5210ca1b2e3',
			'label' => 'Responses',
			'name' => 'responses',
			'type' => 'group',
			'instructions' => 'Responses to the viewer whenever a form is submitted.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5c5210e21b2e4',
					'label' => 'On Successful Submission',
					'name' => 'success',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => '',
				),
				array(
					'key' => 'field_5c5210f01b2e5',
					'label' => 'On Failed Submission',
					'name' => 'failed',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => '',
				),
				array(
					'key' => 'field_5c5210ff1b2e6',
					'label' => 'When a Technical Issue Appears',
					'name' => 'technical',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => '',
				),
				array(
					'key' => 'field_5c52119f1be85',
					'label' => 'Disclaimer Message on Email',
					'name' => 'disclaimer',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => '',
				),
			),
		),
		array(
			'key' => 'field_5c4fa12bc5503',
			'label' => 'CRM Details',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c56112875d45',
			'label' => 'CRM Submission URL',
			'name' => 'crm-url',
			'type' => 'url',
			'instructions' => 'The URL this form submits to. Leaving this blank will disable CRM submissions.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e177eea7460c',
			'label' => 'GUID Submission',
			'name' => 'include-guid',
			'type' => 'true_false',
			'instructions' => 'Set form behaviour on how to handle GUID strings. This is setup by Javascript functions on the front end of the website.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Exclude',
			'ui_off_text' => 'Include',
		)
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'forms',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'slug',
		6 => 'author',
		7 => 'format',
		8 => 'page_attributes',
		9 => 'featured_image',
		10 => 'categories',
		11 => 'tags',
		12 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c58f88c9cbfd',
	'title' => 'Custom Post Types',
	'fields' => array(
		array(
			'key' => 'field_5c58fc71d28d9',
			'label' => 'Post Type',
			'name' => 'post-type',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5c58fcfbd28de',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Create Post Type',
			'sub_fields' => array(
				array(
					'key' => 'field_5c5ccdd8f0efe',
					'label' => 'Post Type Details',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5c5e11926281a',
					'label' => 'Slug',
					'name' => 'slug',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c64a2e8f769f',
					'label' => 'URL Base',
					'name' => 'rewrite',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c58fcfbd28de',
					'label' => 'Icon',
					'name' => 'dashicon',
					'type' => 'kld_dashicon',
					'instructions' => 'Sets the icon for this post type on the menu.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'font_size' => 14,
				),
				array(
					'key' => 'field_5c58fc80d28da',
					'label' => 'Label',
					'name' => 'label',
					'type' => 'group',
					'instructions' => 'Sets the name for this post type.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'sub_fields' => array(
						array(
							'key' => 'field_5c58fcb0d28db',
							'label' => 'Singular',
							'name' => 'singular',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5c58fcb8d28dc',
							'label' => 'Plural',
							'name' => 'plural',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5c5cd49fc1d74',
							'label' => 'Menu Name',
							'name' => 'menu',
							'type' => 'text',
							'instructions' => 'Defaults to "Plural" if left blank.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array(
					'key' => 'field_5c58fec1d28e2',
					'label' => 'Hierarchical',
					'name' => 'hierarchical',
					'type' => 'true_false',
					'instructions' => 'Can have sub-posts.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_5c58fccad28dd',
					'label' => 'Visibility',
					'name' => 'public',
					'type' => 'true_false',
					'instructions' => 'Sets visibility for this post.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'Visible',
					'ui_off_text' => 'Private',
				),
				array(
					'key' => 'field_5c58fd0dd28df',
					'label' => 'User Acess',
					'name' => 'capability',
					'type' => 'repeater',
					'instructions' => 'Sets role types that can access this post type.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_5c58fd47d28e0',
					'min' => 1,
					'max' => 0,
					'layout' => 'table',
					'button_label' => 'Add Access',
					'sub_fields' => array(
						array(
							'key' => 'field_5c58fd47d28e0',
							'label' => 'Capability',
							'name' => 'capability',
							'type' => 'select',
							'instructions' => 'Sets the capability for role assignment. Setting a value to "All Activities" will be overridden by every existing capability type set before or after this.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'all' => 'All Activities',
								'edit_post' => 'Edit Entries',
								'read_post' => 'Read Entries',
								'delete_post' => 'Delete Entries',
								'delete_posts' => 'Delete Multiple Entries',
								'edit_posts' => 'Edit Multiple Entries',
								'edit_others_posts' => 'Edit Submitted Entries',
								'publish_posts' => 'Publish Entries',
								'read_private_posts' => 'Read Private Entries',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5c58fe16d28e1',
							'label' => 'User Type',
							'name' => 'role',
							'type' => 'select',
							'instructions' => 'Sets the user type for this capability.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'moderate_comments' => 'Client',
								'create_users' => 'Administrator',
								'setup_network' => 'Webmaster',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
					),
				),
				array(
					'key' => 'field_5c58fedad28e3',
					'label' => 'Menu Position',
					'name' => 'position',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 9,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'cpt',
			),
		),
	),
	'menu_order' => 5,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c64a3e539103',
	'title' => 'Viewable Pages',
	'fields' => array(
		array(
			'key' => 'field_5e225bb2d8d77',
			'label' => 'Navigation State',
			'name' => 'navigation_state',
			'type' => 'true_false',
			'instructions' => 'Sets visibility for navigation bar that links up the whole site.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Hidden',
			'ui_off_text' => 'Visible',
		),
		array(
			'key' => 'field_5c64a3e99588e',
			'label' => 'Site Navigation',
			'name' => 'site_navigation',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5c64a4069588f',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Page',
			'sub_fields' => array(
				array(
					'key' => 'field_5c64a4069588f',
					'label' => 'Target',
					'name' => 'target',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array(
					'key' => 'field_5c5dd44829a9c',
					'label' => 'Visible',
					'name' => 'visible',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'Shown',
					'ui_off_text' => 'Hidden',
				),
			),
		)
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'cpt',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c06eb56d24c1',
	'title' => 'Visibility and Meta Tags',
	'fields' => array(
		array(
			'key' => 'field_5c06eb5f920b5',
			'label' => 'Title',
			'name' => 'seo-title',
			'type' => 'text',
			'instructions' => 'Fill this in if you wish to replace the page title. Otherwise it will use the auto-generated title on what is filled in the "title" input bar on the top of this page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c06ebbf920b6',
			'label' => 'Description',
			'name' => 'seo-description',
			'type' => 'textarea',
			'instructions' => 'The description for this page to be seen by search engines. Defaults to website tagline if not filled in.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5c06ebde920b7',
			'label' => 'Thumbnail',
			'name' => 'seo-thumbnail',
			'type' => 'image',
			'instructions' => 'The image that appears when you share this page across social media websites. Leaving this blank will default to the one specified under Settings > General. Recommended size 1200x630 or greater with same proportion.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => 1200,
			'min_height' => 630,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '!=',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '!=',
				'value' => 'page',
			),
		),
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'temp-page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c5cd11d4dc8c',
	'title' => 'Custom Taxonomies',
	'fields' => array(
		array(
			'key' => 'field_5c5cd4c329892',
			'label' => 'Taxonomy',
			'name' => 'taxonomy',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5c5cd54c29898',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Assign New Taxonomy',
			'sub_fields' => array(
				array(
					'key' => 'field_5c5cd56229899',
					'label' => 'General Details',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5c5cd54c29898',
					'label' => 'Slug',
					'name' => 'rewrite',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c5cd4e329894',
					'label' => 'Labels',
					'name' => 'labels',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c5cd50429895',
							'label' => 'Singular',
							'name' => 'singular',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5c5cd50c29896',
							'label' => 'Plural',
							'name' => 'plural',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5c5cd51329897',
							'label' => 'Menu',
							'name' => 'menu',
							'type' => 'text',
							'instructions' => 'Defaults to "Plural" if left blank.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array(
					'key' => 'field_5c5cd4d029893',
					'label' => 'Target(s)',
					'name' => 'target',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 1,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add Target',
					'sub_fields' => array(
						array(
							'key' => 'field_5c5e173596cca',
							'label' => 'Post Type',
							'name' => 'type',
							'type' => 'kld_post_type',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'font_size' => 14,
						),
					),
				),
				array(
					'key' => 'field_5c5cd5792989a',
					'label' => 'Data Handling',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5c5cd6002989b',
					'label' => 'Hierarchy',
					'name' => 'hierarchical',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'Vertical (Category)',
					'ui_off_text' => 'Lateral (Post Tag)',
				),
				array(
					'key' => 'field_5c5cd62c2989c',
					'label' => 'Edit Post Window',
					'name' => 'show_ui',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'Show in Edit Window',
					'ui_off_text' => 'Hide from Edit Screen',
				),
				array(
					'key' => 'field_5c5cd6792989d',
					'label' => 'Post List Window',
					'name' => 'show_admin_column',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'Shown in Post Listing',
					'ui_off_text' => 'Hidden in Post Lists',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'cpt',
			),
		),
	),
	'menu_order' => 6,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c5e22f758544',
	'title' => 'Feature Overrides',
	'fields' => array(
		array(
			'key' => 'field_5c5e23064b336',
			'label' => 'Menu',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c5e23214b337',
			'label' => 'Hide Menu Items',
			'name' => 'hide_menu',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5c5e232d4b338',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Hide a Menu Item',
			'sub_fields' => array(
				array(
					'key' => 'field_5c5e232d4b338',
					'label' => 'Menu Slug',
					'name' => 'menu_slug',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c5e23814b339',
					'label' => 'Hidden From',
					'name' => 'hidden_from',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'everyone' => 'Everyone',
						'setup_network' => 'Client',
						'create_users' => 'Other Users',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_5c5e2418a3996',
			'label' => 'Submenu',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c5e245aa3998',
			'label' => 'Hide Submenu Items',
			'name' => 'hide_submenu',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5c5e232d4b338',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Hide a Menu Item',
			'sub_fields' => array(
				array(
					'key' => 'field_5c5e245aa3999',
					'label' => 'Menu Slug',
					'name' => 'menu_slug',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c5e2470a399b',
					'label' => 'Submenu Slug',
					'name' => 'submenu_slug',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c5e245aa399a',
					'label' => 'Hidden From',
					'name' => 'hidden_from',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'everyone' => 'Everyone',
						'setup_network' => 'Client',
						'create_users' => 'Other Users',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_5c5e248ea399c',
			'label' => 'Dashboard',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c5e2552a39a3',
			'label' => 'Wordpress.com Blog',
			'name' => 'side-core-dashboard_primary',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'Visible',
			'ui_off_text' => 'Hidden',
		),
		array(
			'key' => 'field_5c5e249ea399d',
			'label' => 'Quick Draft',
			'name' => 'side-core-dashboard_quick_press',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'Visible',
			'ui_off_text' => 'Hidden',
		),
		array(
			'key' => 'field_5c5e24dca399f',
			'label' => 'At a Glance',
			'name' => 'normal-core-dashboard_right_now',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'Shown',
			'ui_off_text' => 'Hidden',
		),
		array(
			'key' => 'field_5c5e31ca58d38',
			'label' => 'Activity',
			'name' => 'normal-core-dashboard_activity',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'Visible',
			'ui_off_text' => 'Hidden',
		),
		array(
			'key' => 'field_5c5e2508a39a1',
			'label' => 'Recent Drafts',
			'name' => 'normal-core-dashboard_recent_drafts',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'Visible',
			'ui_off_text' => 'Hidden',
		),
		array(
			'key' => 'field_5c5e251ca39a2',
			'label' => 'Recent Comments',
			'name' => 'normal-core-dashboard_recent_comments',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'Visible',
			'ui_off_text' => 'Hidden',
		),
		array(
			'key' => 'field_5c5e259a72775',
			'label' => 'Features and Metaboxes',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c5e25a872776',
			'label' => 'Hide Default Post Features',
			'name' => 'remove-post-features',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'sp-thumbnail' => 'Featured Image',
				'sp-author' => 'Author Field',
				'sp-excerpt' => 'Excerpt Field',
				'sp-trackbacks' => 'Trackbacks Meta Box',
				'sp-custom-fields' => 'Custom Field Values',
				'sp-revisions' => 'Revisions',
				'sp-post-attributes' => 'Post Attributes',
				'sp-comments' => 'Comments',
				'sp-discussion' => 'Discussion Area',
				'mb-formatdiv' => 'Post Formats',
				'mb-categorydiv' => 'Post Categories',
				'mb-tagsdiv-post_tag' => 'Post Tags',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 1,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5c5e27d172779',
			'label' => 'Hide Default Page Features',
			'name' => 'remove-page-features',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'sp-thumbnail' => 'Featured Image',
				'sp-author' => 'Author Field',
				'sp-trackbacks' => 'Trackbacks',
				'sp-custom-fields' => 'Custom Field Values',
				'sp-revisions' => 'Revisions',
				'sp-page-attributes' => 'Page Attributes',
				'sp-comments' => 'Comments',
				'sp-discussion' => 'Discussion Area',
				'sp-editor' => 'Default Text Editor',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 1,
			'return_format' => 'value',
			'save_custom' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'cpt',
			),
		),
	),
	'menu_order' => 10,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c9562abbda41',
	'title' => 'External Resources',
	'fields' => array(
		array(
			'key' => 'field_5c9563b73c991',
			'label' => 'Javascript',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c9562b13c98b',
			'label' => 'Externals',
			'name' => 'ext-js',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5c95632f3c98d',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add External Javascript',
			'sub_fields' => array(
				array(
					'key' => 'field_5e2780d7b751d',
					'label' => 'Source Attributes',
					'name' => 'js-resource',
					'type' => 'group',
					'instructions' => 'Sets the Javascript resource to be loaded in.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'sub_fields' => array(
						array(
							'key' => 'field_5e277eea7460c',
							'label' => 'Type',
							'name' => 'is-file',
							'type' => 'true_false',
							'instructions' => 'Sets the source type for this script. You may choose to upload a file or link the script externally via a URL.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => 'File',
							'ui_off_text' => 'URL',
						),
						array(
							'key' => 'field_5e277f6e7460f',
							'label' => 'Source',
							'name' => 'js-script',
							'type' => 'group',
							'instructions' => 'The script source. Files are limited to .js files only. URLs have to be prefixed with an https:// to prevent issues with the new SSL protocols set in place by Google.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5e277f307460d',
									'label' => 'URL',
									'name' => 'url',
									'type' => 'url',
									'instructions' => 'The script\'s URL.',
									'required' => 1,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5e277eea7460c',
												'operator' => '!=',
												'value' => '1',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5e277f497460e',
									'label' => 'File',
									'name' => 'file',
									'type' => 'file',
									'instructions' => 'The script file. JS only.',
									'required' => 1,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5e277eea7460c',
												'operator' => '==',
												'value' => '1',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'library' => 'all',
									'min_size' => '',
									'max_size' => '',
									'mime_types' => 'js',
								),
							),
						),
						array(
							'key' => 'field_5e277e147460b',
							'label' => 'Availability',
							'name' => 'availability',
							'type' => 'checkbox',
							'instructions' => 'Determine where this script will be enqueued. Custom values equate to the hook (WordPress API) you wish to enqueue the script on.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'front' => 'Front End',
								'admin' => 'WordPress Admin (Global)',
								'production' => 'Production Only',
							),
							'allow_custom' => 1,
							'save_custom' => 0,
							'default_value' => array(
								0 => 'front',
							),
							'layout' => 'vertical',
							'toggle' => 0,
							'return_format' => 'value',
						),
					),
				),
				array(
					'key' => 'field_5e277d6974608',
					'label' => 'Attributes',
					'name' => 'js-attributes',
					'type' => 'repeater',
					'instructions' => 'Sets script inclusion attributes.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_5e277df174609',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => 'Add Attribute',
					'sub_fields' => array(
						array(
							'key' => 'field_5e277df174609',
							'label' => 'Key',
							'name' => 'key',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5e277dfc7460a',
							'label' => 'Value',
							'name' => 'value',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
			),
		),
		array(
			'key' => 'field_5c95640c3c99b',
			'label' => 'Inline',
			'name' => 'inline-js',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5c95632f3c98d',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Inline Code',
			'sub_fields' => array(
				array(
					'key' => 'field_5c95640c3c99c',
					'label' => 'Availability',
					'name' => 'predeployed',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'Everywhere',
					'ui_off_text' => 'Production',
				),
				array(
					'key' => 'field_5c95640c3c99d',
					'label' => 'Javascript Code',
					'name' => 'src',
					'type' => 'acf_code_field',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'mode' => 'javascript',
					'theme' => 'yeti',
				)
			),
		),
		array(
			'key' => 'field_5c9564e737a44',
			'label' => 'CSS',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c9564f337a45',
			'label' => 'Externals',
			'name' => 'ext-css',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5c95632f3c98d',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add CSS',
			'sub_fields' => array(
				array(
					'key' => 'field_5e277eea7471c',
					'label' => 'Type',
					'name' => 'is-file',
					'type' => 'true_false',
					'instructions' => 'Sets the source type for this script. You may choose to upload a file or link the script externally via a URL.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'File',
					'ui_off_text' => 'URL',
				),
				array(
					'key' => 'field_5e277f6e7470f',
					'label' => 'Source',
					'name' => 'css-src',
					'type' => 'group',
					'instructions' => 'The script source. Files are limited to .js files only. URLs have to be prefixed with an https:// to prevent issues with the new SSL protocols set in place by Google.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5e277f307470d',
							'label' => 'URL',
							'name' => 'url',
							'type' => 'url',
							'instructions' => 'The stylesheet\'s URL.',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5e277eea7471c',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5e277f497470e',
							'label' => 'File',
							'name' => 'file',
							'type' => 'file',
							'instructions' => 'The stylesheet file. CSS only.',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5e277eea7471c',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => 'css',
						),
					),
				),
				array(
					'key' => 'field_5e277e146460b',
					'label' => 'Availability',
					'name' => 'availability',
					'type' => 'checkbox',
					'instructions' => 'Determine where this script will be enqueued. Custom values equate to the hook (WordPress API) you wish to enqueue the script on.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'front' => 'Front End',
						'admin' => 'WordPress Admin (Global)',
					),
					'allow_custom' => 0,
					'save_custom' => 0,
					'default_value' => array(
						0 => 'front',
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
				)
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'cpt',
			),
		),
	),
	'menu_order' => 11,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c78b3c7b749a',
	'title' => 'Recaptcha',
	'fields' => array(
		array(
			'key' => 'field_5c78b63dc3a28',
			'label' => 'Site Key',
			'name' => 'recap-key',
			'type' => 'text',
			'instructions' => 'The key given by the recaptcha account.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5cace0f3fcac7',
			'label' => 'ReCaptcha&trade; Secret',
			'name' => 'recap-secret',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c78b65ac3a29',
			'label' => 'Test Failure Response',
			'name' => 'recap-fail',
			'type' => 'textarea',
			'instructions' => 'The response the user gets when s/he fails a Recaptcha test.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'forms',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5ce86269a19d0',
	'title' => 'Pre-Initalize',
	'fields' => array(
		array(
			'key' => 'field_5ce8627238213',
			'label' => 'Preloaded Images',
			'name' => 'image-preload',
			'type' => 'repeater',
			'instructions' => 'These images will be preloaded before the initial loading sequence begins. If any image or image composite in this list is not used by any of the content on the site, it will not be loaded at all.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5ce862c638214',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Image',
			'sub_fields' => array(
				array(
					'key' => 'field_5ce862c638214',
					'label' => 'Type',
					'name' => 'type',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'image' => 'Image File',
						'vector' => 'Vector Composite',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5ce8634038215',
					'label' => 'Image File',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5ce862c638214',
								'operator' => '==',
								'value' => 'image',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'jpg, png, jpeg, bmp, gif',
				),
				array(
					'key' => 'field_5ce863d938216',
					'label' => 'Image Files',
					'name' => 'composite',
					'type' => 'vector_image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5ce862c638214',
								'operator' => '==',
								'value' => 'vector',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'raster_instructions' => '',
					'vector_instructions' => '',
					'font_size' => 14,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'cpt',
			),
		),
	),
	'menu_order' => 4,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_602dbb16db8ac',
	'title' => 'Temporary Page',
	'fields' => array(
		array(
			'key' => 'field_602dbb22639b3',
			'label' => 'Introduction',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'This is a temporary page. Enabling this will disable all other pages as well as the header navigation. These pages are stand alone and cannot coexist with the rest of the other pages on the website. Turning this on, however does not remove the capability to edit other pages hosted on this website.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_602dbb62639b4',
			'label' => 'State',
			'name' => 'teaser-active',
			'type' => 'true_false',
			'instructions' => 'Activate temporary page mode?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Active',
			'ui_off_text' => 'Inactive',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'temp-page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
?>